//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusAPP.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.AnimalTraining = new HashSet<AnimalTraining>();
        }
    
        public int Animal_ID { get; set; }
        public string Animal_Name { get; set; }
        public int Animal_Age { get; set; }
        public int Gender_ID { get; set; }
        public decimal Animal_Height { get; set; }
        public string Recommend_Food { get; set; }
        public string Care { get; set; }
        public int User_ID { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalTraining> AnimalTraining { get; set; }
    }
}
