//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusAPP.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public int Artist_ID { get; set; }
        public int User_ID { get; set; }
        public int ArtistType_ID { get; set; }
        public Nullable<int> Perfomance_Number { get; set; }
    
        public virtual ArtistType ArtistType { get; set; }
        public virtual User User { get; set; }
    }
}
